# Generated by Django 4.2.6 on 2023-10-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='is_staff',
        ),
    ]
