# Generated by Django 4.2.6 on 2023-10-15 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_owner_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 2, 46, 16, 911754, tzinfo=datetime.timezone.utc)),
        ),
    ]
