# Generated by Django 4.2.6 on 2023-10-15 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('date_invited', models.DateTimeField(default=datetime.datetime(2023, 10, 15, 2, 45, 58, 242499, tzinfo=datetime.timezone.utc))),
                ('date_joined', models.DateTimeField()),
                ('password', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
