# Generated by Django 4.2.6 on 2023-10-15 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_invited',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 2, 46, 16, 912521, tzinfo=datetime.timezone.utc)),
        ),
    ]
